# Note -- this is a development tool and not intended as a means to distribute
# this program.
FROM amazonlinux:2
RUN yum install -y git golang nmap-ncat lynx

WORKDIR /root/go/src/github.com/petderek

ADD . .

